# Generated by Django 3.2.6 on 2021-08-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
