# Generated by Django 3.2.6 on 2021-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isEdited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='isEdited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
