# Generated by Django 3.2.6 on 2021-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'love'), ('F', 'follow'), ('M', 'message'), ('R', 'reply'), ('RT', 'retweet')], default=None, max_length=2),
        ),
    ]
