# Generated by Django 3.2.6 on 2021-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'love'), ('F', 'follow'), ('M', 'message'), ('R', 'reply'), ('RT', 'retweet'), ('LR', 'love_comment')], default=None, max_length=2),
        ),
    ]
